# Generated by Django 4.2.7 on 2023-11-24 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_content_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 9, 47, 54, 470861)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
